version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task-frontend-prod
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - task-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task-backend-prod
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped
    networks:
      - task-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: task-nginx-prod
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - task-network

networks:
  task-network:
    driver: bridge