version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: task-frontend-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - task-network

  backend:
    build: ./backend
    container_name: task-backend-dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
    networks:
      - task-network

  nginx:
    build: ./nginx
    container_name: task-nginx-dev
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    networks:
      - task-network

networks:
  task-network:
    driver: bridge